apiVersion: autoscaling/v1
# Tipo autoescalado horizontal
kind: HorizontalPodAutoscaler
metadata:
  name: autoescalado
spec:
  # Indicamos a quién se aplica el auto-escalado
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: despliegueivan
  # Mínimo y máximo de réplicas
  minReplicas: 5
  maxReplicas: 10
  # Máximo de CPU a usar durante el auto-escalado
  targetCPUUtilizationPercentage: 50
