# Indicamos la versión de la API
apiVersion: apps/v1
# Indicamos que este fichero es de un despliegue
kind: Deployment
# Metadatos del despliegue
metadata:
  name: despliegueivan
# Características del despliegue
spec:
  # Al inicio 3 réplicas (luego si queremos activamos autoescalado)
  replicas: 3
  # Selector de los pods
  selector:
    matchLabels:
      app: despliegueivan
  # Plantilla de los pods
  template:
    # Metadatos de los pods
    metadata:
      labels:
        app: despliegueivan
    # Caracteristicas de los pods
    spec:
      # Contenedor del pod
      containers:
        # Nombre, imagen y puerto expuesto
        - name: miapp
          image: sergarb1/flaskparakubernetes
          ports:
            - containerPort: 6000
